replicaCount: 1
image:
  repository: "docker.grubstack.app/production/grubstack-core-api"
  tag: "latest"
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
customer:
  host: api.grubstack.app
  tenantId: abcdef123456
  accessToken: abcdefg
  webAppUrl: https://order.grubstack.app
  revalidateSecret: changeme
  productionApiUrl: https://prod-api.grubstack.app/v1
database:
  host: localhost
  name: grubstack_core
  port: 5432
  user: grubstack
  password: grubstack
  ssl: prefer
  production: grubstack
auth0:
  domain: us.auth0.com
  audience: https://api.grubstack.app/v1
mail:
  server: mail.grubstack.app
  port: "587"
  useTls: "no"
  useSsl: "no"
  username: api@grubstack.app
  password: changeme
  defaultSender: "GrubStack <api@grubstack.app>"
