replicaCount: 1
image:
  repository: "docker.grubstack.app/production/grubstack-web"
  tag: "latest"
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 3000
customer:
  host: web.grubstack.app
  apiUrl: https://api.grubstack.app/v1
  accessToken: abcdefg
  squareAppId: abcdefg
app:
  nodeEnv: production
