replicaCount: 1
image:
  repository: "docker.grubstack.app/production/grubstack-web"
  tag: "latest"
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 3000
customer:
  host: web.grubstack.app
  apiUrl: api.grubstack.app
  corporateUrl: grubstack.app
  siteUrl: web.grubstack.app
  tenantId: abcdefg
  slug: abcd123
auth0:
  domain: auth0.com
  clientId: abcdefg
app:
  nodeEnv: production
