apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: production-cred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: API_URL
              value: "{{ .Values.customer.apiUrl }}"
            - name: PRODUCTION_URL
              value: "{{ .Values.customer.productionUrl }}"
            - name: SITE_URL
              value: "{{ .Values.customer.siteUrl }}"
            - name: AUTH_DOMAIN
              value: "{{ .Values.auth0.domain }}"
            - name: AUTH_CLIENT_ID
              value: "{{ .Values.auth0.clientId }}"
            - name: TENANT_ID
              value: "{{ .Values.customer.tenantId }}"
            - name: NODE_ENV
              value: "{{ .Values.app.nodeEnv }}"
            - name: APP_SLUG
              value: "{{ .Values.customer.slug }}"
            - name: ACCESS_TOKEN
              value: "{{ .Values.customer.accessToken }}"

