pipeline {
    agent any
    parameters {
        string(name: 'ACTION', defaultValue: 'deploy', description: 'deploy or remove')
        string(name: 'SLUG', description: 'Customer slug')
        string(name: 'TENANT_ID', description: 'Tenant UUID')
        string(name: 'ACCESS_TOKEN', description: 'Customer access token')
        string(name: 'DATABASE_HOST', description: 'Database host')
        string(name: 'DATABASE_NAME', description: 'Database name')
        string(name: 'DATABASE_PORT', defaultValue: '5432', description: 'Database port')
        string(name: 'DATABASE_USER', description: 'Database user')
        string(name: 'DATABASE_PASSWORD', description: 'Database password')
        string(name: 'DATABASE_SSL', defaultValue: 'require', description: 'Database SSL mode')
        string(name: 'PRODUCTION_DB', description: 'Production database name')
        string(name: 'PRODUCTION_API_URL', description: 'URL of the prod-api service (e.g. https://prod-api.grubstack.app/v1)')
    }
    stages {
        stage('Deploy') {
            when {
                expression { params.ACTION == 'deploy' }
            }
            steps {
                sh """
                    helm upgrade --install grubstack-core-api-${params.SLUG} /opt/grubstack-helm/grubstack-core-api \\
                        --set customer.host=api-${params.SLUG}.grubstack.app \\
                        --set customer.tenantId=${params.TENANT_ID} \\
                        --set customer.accessToken=${params.ACCESS_TOKEN} \\
                        --set database.host=${params.DATABASE_HOST} \\
                        --set database.name=${params.DATABASE_NAME} \\
                        --set database.port=${params.DATABASE_PORT} \\
                        --set database.user=${params.DATABASE_USER} \\
                        --set database.password=${params.DATABASE_PASSWORD} \\
                        --set database.ssl=${params.DATABASE_SSL} \\
                        --set database.production=${params.PRODUCTION_DB} \\
                        --set customer.productionApiUrl=${params.PRODUCTION_API_URL} \\
                        --set mail.server=\${GS_MAIL_SERVER} \\
                        --set mail.port=\${GS_MAIL_PORT} \\
                        --set mail.useTls=\${GS_MAIL_USE_TLS} \\
                        --set mail.username=\${GS_MAIL_USERNAME} \\
                        --set mail.password=\${GS_MAIL_PASSWORD} \\
                        --set "mail.defaultSender=\${GS_MAIL_DEFAULT_SENDER}" \\
                        --namespace grubstack \\
                        --create-namespace
                    kubectl rollout restart deployment/grubstack-core-api-${params.SLUG} -n grubstack
                """
            }
        }
        stage('Remove') {
            when {
                expression { params.ACTION == 'remove' }
            }
            steps {
                sh "helm uninstall grubstack-core-api-${params.SLUG} --namespace grubstack"
            }
        }
    }
}
