apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: production-cred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TENANT_ID
              value: "{{ .Values.customer.tenantId }}"
            - name: DATABASE_HOST
              value: "{{ .Values.database.host }}"
            - name: DATABASE_NAME
              value: "{{ .Values.database.name }}"
            - name: DATABASE_PORT
              value: "{{ .Values.database.port }}"
            - name: DATABASE_USER
              value: "{{ .Values.database.user }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: DATABASE_SSL
              value: "{{ .Values.database.ssl }}"
            - name: CORPORATE_DB
              value: "{{ .Values.database.corporate }}"
